# Generated by Django 6.1 on 2026-08-27 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_skill_options_alter_skill_name'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('opportunity_type', models.CharField(choices=[('job', 'Emploi'), ('internship', 'Stage'), ('training', 'Formation')], max_length=20, verbose_name='type')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='pays')),
                ('is_remote', models.BooleanField(default=False, verbose_name='télétravail')),
                ('experience_level', models.CharField(blank=True, choices=[('entry', 'Débutant'), ('junior', 'Junior'), ('senior', 'Senior'), ('expert', 'Expert')], max_length=20, verbose_name="niveau d'expérience")),
                ('education_level', models.CharField(blank=True, choices=[('high_school', 'Baccalauréat'), ('bachelor', 'Licence'), ('master', 'Master'), ('doctorate', 'Doctorat')], max_length=20, verbose_name="niveau d'étude")),
                ('contract_type', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('freelance', 'Freelance'), ('n_a', 'Non applicable')], default='n_a', max_length=20, verbose_name='type de contrat')),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='salaire minimum')),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='salaire maximum')),
                ('duration_weeks', models.PositiveIntegerField(blank=True, null=True, verbose_name='durée (semaines)')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending_review', 'En attente de validation'), ('approved', 'Approuvée'), ('published', 'Publiée'), ('rejected', 'Rejetée'), ('closed', 'Clôturée'), ('archived', 'Archivée')], default='draft', max_length=20, verbose_name='statut')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='motif de rejet')),
                ('application_deadline', models.DateField(blank=True, null=True, verbose_name='date limite de candidature')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='date de publication')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='opportunities.category', verbose_name='catégorie')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='organizations.organization', verbose_name='organisation')),
                ('skills', models.ManyToManyField(blank=True, related_name='opportunities', to='core.skill', verbose_name='compétences requises')),
            ],
            options={
                'verbose_name': 'opportunité',
                'verbose_name_plural': 'opportunités',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'opportunity_type'], name='opportuniti_status_75139c_idx'), models.Index(fields=['-created_at'], name='opportuniti_created_1b69e8_idx')],
            },
        ),
    ]
