# Generated by Django 6.1 on 2026-08-28 10:13

import apps.documents.models
import apps.documents.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('cv', 'CV'), ('diploma', 'Diplôme'), ('certificate', 'Certificat'), ('cover_letter', 'Lettre de motivation'), ('other', 'Autre')], max_length=20, verbose_name='type')),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path, validators=[apps.documents.validators.validate_file_size, apps.documents.validators.validate_file_extension, apps.documents.validators.validate_file_mime_type], verbose_name='fichier')),
                ('original_filename', models.CharField(max_length=255, verbose_name='nom original')),
                ('file_size', models.PositiveIntegerField(verbose_name='taille (octets)')),
                ('mime_type', models.CharField(max_length=100, verbose_name='type MIME')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="date d'upload")),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
