# Generated by Django 6.1 on 2026-08-27 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0001_initial'),
        ('profiles', '0002_alter_candidateprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Envoyée'), ('under_review', "En cours d'examen"), ('shortlisted', 'Présélectionnée'), ('interview', 'Entretien proposé'), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('withdrawn', 'Retirée')], default='submitted', max_length=20, verbose_name='statut')),
                ('cover_note', models.TextField(blank=True, verbose_name='message de motivation')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='date de candidature')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='profiles.candidateprofile', verbose_name='candidat')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='opportunities.opportunity', verbose_name='opportunité')),
            ],
            options={
                'verbose_name': 'candidature',
                'verbose_name_plural': 'candidatures',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['opportunity', 'status'], name='application_opportu_56305f_idx')],
                'constraints': [models.UniqueConstraint(fields=('candidate', 'opportunity'), name='unique_application_per_candidate_opportunity')],
            },
        ),
    ]
