# Generated by Django 6.1 on 2026-08-28 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application', verbose_name='candidature')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_documents', to='documents.document', verbose_name='document')),
            ],
            options={
                'verbose_name': 'document de candidature',
                'verbose_name_plural': 'documents de candidature',
                'constraints': [models.UniqueConstraint(fields=('application', 'document'), name='unique_document_per_application')],
            },
        ),
    ]
