# Generated by Django 6.1 on 2026-08-28 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('application_submitted', 'Candidature envoyée'), ('application_status_changed', 'Statut de candidature modifié'), ('opportunity_approved', 'Opportunité approuvée'), ('opportunity_rejected', 'Opportunité rejetée')], max_length=40, verbose_name='type')),
                ('message', models.CharField(max_length=255, verbose_name='message')),
                ('is_read', models.BooleanField(default=False, verbose_name='lue')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
            },
        ),
    ]
